### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by phil-opp** [saibatizoku/font8x8-rs#2]
Hi, your library would be really useful for us! However, I'm not sure whether we can use it with the current license ("The Unlicense"), because there seem to be [a few issues](https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense) around it. For one, we are based in Germany where the something like the “public domain“ does not exist juridically.

So I wanted to ask if you might consider to re-license this library under more proved license such as MIT/Apache? Given the young state of the library and that there are no external contributors the relicensing process should be pretty painless (i.e. just upload a new license file).

**Comment by saibatizoku** [comment]
Hi! Thanks for raising the issue. I hadn't considered that the "public domain" could be interpreted differently in other countries. It should be no problem adding a new license.

It's great to know that the library is useful to you. Thanks!

**Comment by phil-opp** [comment]
Awesome, thank you very much!
