### ISSUE TITLE
Add Glyphs From Unscii

### ISSUE THREAD

**Issue by jansol** [saibatizoku/font8x8-rs#8]
[unscii](http://pelulamu.net/unscii/) contains a variety of character ranges not present in this font. The full version is GPL-licensed so not compatible with this crate, but the basic versions are in public domain so taking glyphs from those should be fine.

On the technical side this should be very easy as well, since the hex files already list the unicode codepoints for each glyph and most versions of the font are specifically 8x8 bitmaps. It is worth noting though that some glyphs are stored as full-width and actually 8x16. Not sure how those should be handled when converting.

Unscii contains at least Cyrillic, Hebrew, Arabic, an extensive set of PETSCII symbols and Katakana.

I'm not sure if increasing the unicode coverage is a goal for this crate though? Feel free to close if that is not the case.

**Comment by saibatizoku** [comment]
@jansol I think that unscii deserves a crate of its own. This crate was born as a port from an C-header files to Rust, and I think that that's as far as it should go. Thanks for the proposal, I think that I'd like to take a shot a making unscii-rs, but I need to have some spare time for it. I'd also be glad to help out if you or anyone decides to start something along those lines.

I'm closing this issue.
